logging:
    level:
      root: INFO
server:
    port: 8081
spring:
  datasource:
      continue-on-error: true
      driver-class-name: org.postgresql.Driver
      initialization-mode: always
      initialize: true
      password: gopal
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
